name: Build and Push Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build and push the Docker image
        run: |
          docker build --push --platform linux/arm/v7 -t 08021986/ping-neo4j:${GITHUB_SHA} -t 08021986/ping-neo4j:latest .
